package si.eclectic.complaints.da.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CbAttachmentTypeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCbAttachmentTypeAllPropertiesEquals(CbAttachmentType expected, CbAttachmentType actual) {
        assertCbAttachmentTypeAutoGeneratedPropertiesEquals(expected, actual);
        assertCbAttachmentTypeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCbAttachmentTypeAllUpdatablePropertiesEquals(CbAttachmentType expected, CbAttachmentType actual) {
        assertCbAttachmentTypeUpdatableFieldsEquals(expected, actual);
        assertCbAttachmentTypeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCbAttachmentTypeAutoGeneratedPropertiesEquals(CbAttachmentType expected, CbAttachmentType actual) {
        assertThat(expected)
            .as("Verify CbAttachmentType auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCbAttachmentTypeUpdatableFieldsEquals(CbAttachmentType expected, CbAttachmentType actual) {
        assertThat(expected)
            .as("Verify CbAttachmentType relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getExtension()).as("check extension").isEqualTo(actual.getExtension()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCbAttachmentTypeUpdatableRelationshipsEquals(CbAttachmentType expected, CbAttachmentType actual) {}
}
