package si.eclectic.complaints.da.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CbComplaintChannelAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCbComplaintChannelAllPropertiesEquals(CbComplaintChannel expected, CbComplaintChannel actual) {
        assertCbComplaintChannelAutoGeneratedPropertiesEquals(expected, actual);
        assertCbComplaintChannelAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCbComplaintChannelAllUpdatablePropertiesEquals(CbComplaintChannel expected, CbComplaintChannel actual) {
        assertCbComplaintChannelUpdatableFieldsEquals(expected, actual);
        assertCbComplaintChannelUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCbComplaintChannelAutoGeneratedPropertiesEquals(CbComplaintChannel expected, CbComplaintChannel actual) {
        assertThat(expected)
            .as("Verify CbComplaintChannel auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCbComplaintChannelUpdatableFieldsEquals(CbComplaintChannel expected, CbComplaintChannel actual) {
        assertThat(expected)
            .as("Verify CbComplaintChannel relevant properties")
            .satisfies(
                e -> assertThat(e.getComplaintChannelName()).as("check complaintChannelName").isEqualTo(actual.getComplaintChannelName())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCbComplaintChannelUpdatableRelationshipsEquals(CbComplaintChannel expected, CbComplaintChannel actual) {}
}
