package si.eclectic.complaints.da.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CbComplaintFieldAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCbComplaintFieldAllPropertiesEquals(CbComplaintField expected, CbComplaintField actual) {
        assertCbComplaintFieldAutoGeneratedPropertiesEquals(expected, actual);
        assertCbComplaintFieldAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCbComplaintFieldAllUpdatablePropertiesEquals(CbComplaintField expected, CbComplaintField actual) {
        assertCbComplaintFieldUpdatableFieldsEquals(expected, actual);
        assertCbComplaintFieldUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCbComplaintFieldAutoGeneratedPropertiesEquals(CbComplaintField expected, CbComplaintField actual) {
        assertThat(expected)
            .as("Verify CbComplaintField auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCbComplaintFieldUpdatableFieldsEquals(CbComplaintField expected, CbComplaintField actual) {
        assertThat(expected)
            .as("Verify CbComplaintField relevant properties")
            .satisfies(e -> assertThat(e.getComplaintFieldName()).as("check complaintFieldName").isEqualTo(actual.getComplaintFieldName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCbComplaintFieldUpdatableRelationshipsEquals(CbComplaintField expected, CbComplaintField actual) {}
}
